package com.tpad.ihome.inter;

public enum RZ_EVENT
{
	NULL, // 0
	PINGTEST, // 1
	SERVER_BUSY, // 2
	SERVER_SHUTDOWN, // 3
	UPDATE_GROUP, // 4
	ADD_DEVICE, // 5
	DEL_DEVICE, // 6
	ACC_DEVICE, // 7
	RCV_DEVICE, // 8
	LOCAL_DEVICE_EVENT, // 9
	LOCAL_DEVICE_EVENT_ACK, // 10
	LOGIN, // 11
	LOGOUT, // 12
	LOGIN_SUCCESS, // 13
	LOGIN_FAILED_INVALID, // 14
	LOGIN_FAILED_KICKED_OUT, // 15
	LOGIN_FAILED_BLOCKED, // 16
	CALL_TO, // 17
	CALL_ACCEPT, // 18
	CALL_REJECT, // 19
	CALL_END, // 20
	CALL_GIVEUP, // 21
	CALL_FAILED_NOT_ONLINE, // 22 
	CALL_FAILED_NO_RESPOND, // 23
	CALL_FAILED_REJECT, // 24
	CALL_REQUEST, // 25
	CALL_START, // 26
	CALL_LINK_TEST_LOCAL, // 27  
	CALL_LINK_TEST_REMOTE, // 28
	CALL_LINK_TEST_FAIL, // 29
	CALL_LINK_TEST_OK, // 30
	CALL_LINK_TEST_SERV_TRY, // 31
	CALL_NAT_SERV_LINK_TEST, // 32
	CALL_NAT_P2P_LINK_TEST, // 33
	CALL_NAT_P2P_RESULT, // 34
	GET_DEVICE_INFO, // 35
	SET_DEVICE_INFO, // 36
	NOTIFY_DEVICE_INFO, // 37
	NOTIFY_ONLINE_STATUS, // 38  
	SEND_MSG, // 39
	SEND_MSG_RESULT, // 40
	SEND_FILE, // 41
	SEND_FILE_RESULT, // 42
	INFO_DOWNLOAD_CHECK, // 43
	COUNT;    
}
